### ISSUE TITLE
How to ignore property private static on Vertex

### ISSUE THREAD

**Issue by buiminhhuy** [gjrwebber/spring-data-gremlin#28]
example:
I have a class:
UserAccount{
   private static final long serialVersionUID = 1L;

   @Value("${app.md5encode.salt}")
   private static final String SALT = "aaaa";
  // other properties
}

When generating schema, above properties static final should be not created. wrong generate schema, see red zone below image.
![useraccount](https://cloud.githubusercontent.com/assets/568664/9428998/86b96cfa-49eb-11e5-9ce3-c15febee2f50.png)

**Comment by gjrwebber** [comment]
Yes, that sounds about right. Static fields should not be serialised.
