### ISSUE TITLE
Circular reference detection

### ISSUE THREAD

**Issue by binaryblake** [gjrwebber/spring-data-gremlin#37]
If I have a vertex that has an edge to another vertex of the same type, it would be nice to prevent infinite looping on query. Simplified Example:

```
@Vertex
class Question{
  @Id
  String id
  @LinkVia
  Set<SubQuestion> questions
}

@Edge
class SubQuestion{
  @Id
  String id
  @FromVertex
  Question from
  @ToVertex
  Question to
}
```

If I create edges between questions AND set the FromVertex, I will get a circular reference and a findOne() query will be in an infinite loop. I can get around this by only setting ToVertex, but then I lose a direction. Being able to fetch lazily might also be a good solution here, related to #6

**Comment by gjrwebber** [comment]
Hi Blake, I think I have fixed this in the latest SNAPSHOT (just uploaded). Can you please download the latest and give it a try? 

Thanks,
Graham

**Comment by binaryblake** [comment]
Will do - thanks for the quick response

**Comment by binaryblake** [comment]
No luck. Here is my simple graph set up:

```
Question q = new Question();
q.setText("test question 1?");
repo.save(q);

Question q2 = new Question();
q2.setText("sub question 2 on true answer?");
repo.save(q2);

Question q3 = new Question();
q3.setText("sub question 3 on false answer?");
repo.save(q3);

Set<TrueFalseSubQuestion> subQuestions = new HashSet<TrueFalseSubQuestion>();

TrueFalseSubQuestion q_q2 = new TrueFalseSubQuestion();
q_q2.setFrom(q);
q_q2.setTo(q2);
q_q2.setConditional(true);
subQuestions.add(q_q2);

TrueFalseSubQuestion q_q3 = new TrueFalseSubQuestion();
q_q3.setFrom(q);
q_q3.setTo(q3);
q_q3.setConditional(false);
subQuestions.add(q_q3);

q.setQuestions(subQuestions);
repo.save(q);
```

Then if I use repo.findAll(). I get the following response:

```
{
"id":"256",
"text":"test question 1?",
"questions":[
{
"id":"1ix40-74-4nit-e8",
"conditional":null,
"from":{
"id":"256",
"text":"test question 1?",
"questions":[
{
"id":"1ix40-74-4nit-e8",
"conditional":null,
"from":{
"id":"256",
"text":"test question 1?",
"questions":[
{
"id":"1ix40-74-4nit-e8",
"conditional":null,
"from":{
"id":"256",
"text":"test question 1?",
"questions":[
{
```

 ..... forever

Ideally it could detect that Question 256 has already been fetched from the graph, and just set the ID or something. I believe that's how spring-data-neo4j does it.

**Comment by gjrwebber** [comment]
Hey Blake, I just added a circular reference to the test domain, see org.springframework.data.gremlin.object.core.domain.Person. It seems to be performing fine, there is no StackOverflowError or anything. Could it be the JSON serialiser that has the issue?

**Comment by gjrwebber** [comment]
@binaryblake could you create a unit test for this?

**Comment by gjrwebber** [comment]
Closed as it cannot be replicated.
