### ISSUE TITLE
Links as entities

### ISSUE THREAD

**Issue by gjrwebber** [gjrwebber/spring-data-gremlin#5]
Currently Objects are mapped to vertices, and links are only given a name. Graph databases allow for complex links, so it would be nice to map a complex link to an Object.

**Comment by buiminhhuy** [comment]
Hi girwebber,
Have you been implement not yet? Can you share it? I can fix bug for you. I are going to implement this problem.
Thanks,
Huy Bui

**Comment by gjrwebber** [comment]
Hi Huy, I am in the middle of implementing this along with #15. Would you be interested in implementing Neo4j  (#8)?

**Comment by buiminhhuy** [comment]
Hi Girwebber,
I have been change my web project from Neo4j to Orientdb, So I am interesting your project to integrate to my project. Before that I used Spring-Data-Neo4j (I leave Neo4j because it is commerce).

**Comment by gjrwebber** [comment]
Well, you'l be interested in #15 as you'll be able to use your Neo4j annotations and switch databases without too much issue.

**Comment by gjrwebber** [comment]
Hi Huy, I just pushed some code on the develop branch which takes care of this issue and #15.

**Comment by buiminhhuy** [comment]
Hi Girwebber,
Great sound, I am implementing base on your framework, but only complete on create schema for relationship, not yet complete add edge. Thanks you very much. If you need I will share it via email.

**Comment by buiminhhuy** [comment]
Hi Girwebber,
Maybe work ok, but I have some concern as: 
       + On your test, I got some warning as: 
"WARNING: Requested command 'create edge type 'was_located' as subclass of 'E'' must be executed outside active transaction: the transaction will be committed and reopen right after it. To avoid this behavior execute it outside a transaction". 
=>Maybe the Schema have not yet created "was_located" before that.
       + Save only RelationshipEntity. (for this case you can support RelationshipRespository, which can add, update, delete the RelationshipEntity, query on properties, ...)
       + Addition you can support OrientDBTemplate (can ref to MongoTemplate, Neo4jTemplate,...), it very usage for users.
       + For schemes with annotations JPA, NEO4J, you can simplify them by creating syntax personal Annotations for your project, such as: (@Entity, @Relationship, @Index, ... something your mind).

**Comment by gjrwebber** [comment]
Hi Huy, thanks for the feedback! I have added #20, #21, #22, #23, #24. Let me know if you are interested in doing any of them?

**Comment by gjrwebber** [comment]
This issue has been implemented on the develop branch as of 3eafe249362fc618ae4284c114d45caee9defeed .
